CREATE TABLE Employee
( EMPID number(10) NOT NULL,
  EMPNAME varchar2(50) NOT NULL,
  EMPAGE number(3) NOT NULL,
  SALARY number(10) NOT NULL,
  ADDRESS varchar2(250) NOT NULL,  
  CONSTRAINT EMPID_PK PRIMARY KEY (EMPID)
);