  CREATE TABLE "SYSTEM"."EMPLOYEE" 
   (	"EMPID" NUMBER(10,0) NOT NULL ENABLE, 
	"EMPADDRESS" VARCHAR2(255 CHAR), 
	"EMPAGE" NUMBER(10,0), 
	"EMPNAME" VARCHAR2(255 CHAR), 
	"SALARY" NUMBER(19,0), 
	  CONSTRAINT EMPID_PK
   PRIMARY KEY ("EMPID")
   );
