-- USER SQL
CREATE USER IMAGEGALLERY IDENTIFIED BY admin 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS

-- ROLES
GRANT "OLAP_XS_ADMIN" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "WFS_USR_ROLE" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "DELETE_CATALOG_ROLE" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "HS_ADMIN_SELECT_ROLE" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "CWM_USER" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "SPATIAL_WFS_ADMIN" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "OLAP_DBA" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "OWB$CLIENT" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "RESOURCE" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "APEX_ADMINISTRATOR_ROLE" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "OWB_DESIGNCENTER_VIEW" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "CTXAPP" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "SPATIAL_CSW_ADMIN" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "GATHER_SYSTEM_STATISTICS" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "AUTHENTICATEDUSER" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "CONNECT" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "HS_ADMIN_EXECUTE_ROLE" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "LOGSTDBY_ADMINISTRATOR" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "JAVADEBUGPRIV" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES_WITH_PUBLIC" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "XDBADMIN" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES_OVER_HTTP" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "EXP_FULL_DATABASE" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "CSW_USR_ROLE" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "OLAPI_TRACE_USER" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "JAVAIDPRIV" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "DBFS_ROLE" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "ADM_PARALLEL_EXECUTE_TASK" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "AQ_ADMINISTRATOR_ROLE" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "JAVA_DEPLOY" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "OEM_MONITOR" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "JAVAUSERPRIV" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "MGMT_USER" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "OWB_USER" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "JAVA_ADMIN" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "JMXSERVER" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "EXECUTE_CATALOG_ROLE" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "SCHEDULER_ADMIN" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "WM_ADMIN_ROLE" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "ORDADMIN" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "AQ_USER_ROLE" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "SELECT_CATALOG_ROLE" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "RECOVERY_CATALOG_OWNER" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "OLAP_USER" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "DBA" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "JAVASYSPRIV" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "XDB_SET_INVOKER" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "IMP_FULL_DATABASE" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "HS_ADMIN_ROLE" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "EJBCLIENT" TO IMAGEGALLERY WITH ADMIN OPTION;
GRANT "OEM_ADVISOR" TO IMAGEGALLERY WITH ADMIN OPTION;
ALTER USER IMAGEGALLERY DEFAULT ROLE "OLAP_XS_ADMIN","WFS_USR_ROLE","DELETE_CATALOG_ROLE","HS_ADMIN_SELECT_ROLE","CWM_USER","SPATIAL_WFS_ADMIN","OLAP_DBA","OWB$CLIENT","RESOURCE","APEX_ADMINISTRATOR_ROLE","OWB_DESIGNCENTER_VIEW","CTXAPP","SPATIAL_CSW_ADMIN","GATHER_SYSTEM_STATISTICS","AUTHENTICATEDUSER","CONNECT","HS_ADMIN_EXECUTE_ROLE","LOGSTDBY_ADMINISTRATOR","JAVADEBUGPRIV","XDB_WEBSERVICES_WITH_PUBLIC","XDBADMIN","XDB_WEBSERVICES_OVER_HTTP","EXP_FULL_DATABASE","CSW_USR_ROLE","OLAPI_TRACE_USER","JAVAIDPRIV","DBFS_ROLE","ADM_PARALLEL_EXECUTE_TASK","AQ_ADMINISTRATOR_ROLE","JAVA_DEPLOY","OEM_MONITOR","XDB_WEBSERVICES","JAVAUSERPRIV","MGMT_USER","OWB_USER","JAVA_ADMIN","JMXSERVER","EXECUTE_CATALOG_ROLE","SCHEDULER_ADMIN","DATAPUMP_IMP_FULL_DATABASE","WM_ADMIN_ROLE","ORDADMIN","AQ_USER_ROLE","DATAPUMP_EXP_FULL_DATABASE","SELECT_CATALOG_ROLE","RECOVERY_CATALOG_OWNER","OLAP_USER","DBA","JAVASYSPRIV","XDB_SET_INVOKER","IMP_FULL_DATABASE","HS_ADMIN_ROLE","EJBCLIENT","OEM_ADVISOR";

-- SYSTEM PRIVILEGES


CREATE TABLE category_img(
    id NUMBER(3) PRIMARY KEY
    , cat_name VARCHAR2(50)
    , description VARCHAR(1000)
    , date_create DATE
);
CREATE TABLE store_img(
    img_no NUMBER(5) PRIMARY KEY
    , img_name VARCHAR2(50) NOT NULL
    , img_description VARCHAR2(1000)
    , img_date_create DATE
    , img_size NUMBER(5)
    , img_user_upload VARCHAR2(50)
    , category_id NUMBER(3) NOT NULL 
    , file_img BLOB
    , FOREIGN KEY (category_id)  REFERENCES category_img(id)
);
CREATE SEQUENCE store_id_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
CREATE SEQUENCE Category_id_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
